baseURL = "https://www.azureninjas.cloud"
languageCode = "en-us"
title = "Azure Ninjas"
theme = "castanet"
googleAnalytics = "UA-108563085-1"
disqusShortname = "azureninjas"
#themesdir = "../.."



[permalinks]
	# page = "/:filename/"
	# about = "/:filename/"
	# episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"

#[[Menu.Main]]
#    name = "Blog"
#    identifier = "blog"
#    url = "blog"

	[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "host"

#  [[Menu.Main]]
#    name = "Authors"
#    identifier = "authors"
#    url = "author"


[params]
site_theme = "light"
site_layout = "grid"
enable_jumbo = "false"
# truncate = "100"
about_logo = "/img/logo.png"
copyright_notice = "Copyright 2017 Azure Ninjas"
itunes_subscribe = "https://itunes.apple.com/us/podcast/azure-ninjas/id1305172229 "
android_subscribe = "http://www.subscribeonandroid.com/www.azureninjas.cloud/episode/index.xml"
google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link="
sticher_subscribe = "https://www.stitcher.com/s?fid=156707&refid=stpr"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Azure Ninjas is a podcast hosted by Microsoft employees that discuss more about Azure than just the new features.  We bring in the Microsoft Product Group to talk about archtiectures, solutions, and more."
media_prefix = "https://www.azureninjas.cloud/media/"
  [params.feed]
    feed_copyright = "Copyright 2017 Azure Ninjas"
    itunes_subtitle = "Azure Ninjas is a podcast hosted by Microsoft employees that discuss more about Azure than just the new features."
    itunes_author = "Elizabeth Graham, Pete Roden" 
    itunes_summary = "Azure Ninjas is a podcast hosted by Microsoft employees that discuss more about Azure than just the new features.  We bring in the Microsoft Product Group to talk about archtiectures, solutions, and more." 
    itunes_owner_name = "Elizabeth Graham, Pete Roden"
    itunes_owner_email = "esenoch@hotmail.com"
    itunes_image = "https://www.azureninjas.cloud/img/logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
	itunes_explicit="No"

  [params.social]
  email         = "azure_ninjas@microsoft.com"
  twitter       = "@azureninjas"
  github        = "codingwithsasquatch"

  [params.authors]


    [params.links]
      [params.links.ado]
        name = "Azure Ninjas"
        url = "https://www.azureninjas.cloud"
